### ISSUE TITLE
It won't work

### ISSUE THREAD

**Issue by lambdalisue** [rbtnn/vim-gloaded#1]
`gloaded.vim` should be in `plugin` directory I guess

**Comment by rbtnn** [comment]
pluginディレクトリに置くと、runtimepathの順番によっては読み込む順番が後のほうになってしまうため、意味がなくなってしまうんじゃないかなーと思いまして。あえてpluginやautoloadに置いてません。
（日本語ですいません

**Comment by lambdalisue** [comment]
たしかに！
